from flask import Flask, request
import os
from app.model.entity.estado import Estado
from app.model.dao.estadoDao import EstadoDao
from app.model.entity.noticia import Noticia
from app.model.dao.noticiaDao import NoticiaDao


app = Flask(__name__, static_folder=os.path.abspath("app/view/static"), template_folder=os.path.abspath("app/view/static"))

exnot1 = Noticia(1, "Hidroxicloroquina não tem eficácia contra a Covid em pacientes leves e moderados, diz estudo brasileiro", " No maior estudo brasileiro publicado até agora, pesquisadores apontam que a hidroxicloroquina não teve eficácia no tratamento da Covid-19 em pacientes com casos leves e moderados atendidos em hospitais. O estudo aponta que, após 15 dias de tratamento, percentuais semelhantes dos pacientes (que tomaram ou não hidroxicloroquina) já estavam em casa sem limitações respiratórias. O percentual de óbitos foi igual em todos os grupos: 3%. A pesquisa, revisada por outros cientistas, foi publicada nesta quinta-feira (23) no The New England Journal of Medicine. O estudo foi realizado pela Coalizão COVID-19, que ainda conduz outros oito estudos sobre o tema, incluindo um sobre a mesma droga no tratamento de casos ambulatoriais, ou seja, em casos mais leves da Covid-19. O grupo é formado por Hospital Israelita Albert Einstein, HCor, Hospital Sírio-Libanês, Hospital Moinhos de Vento, Hospital Alemão Oswaldo Cruz, BP – A Beneficência Portuguesa de São Paulo, o Brazilian Clinical Research Institute (BCRI) e Rede Brasileira de Pesquisa em Terapia Intensiva (BRICNet).", "img/cloroquina.jpg", "video/noticiacloroquinarj.mp4", "Rio de Janeiro", "23/07")
exnot2 = Noticia(2, "RJ tem 274 mortes por Covid-19 confirmadas em 24 horas e chega a 8,4 mil óbitos", "Dados da Secretaria de Saúde do Rio de Janeiro apontam que, nesta quinta-feira (18), estado teve mais 274 mortes confirmadas desde quarta (17) e passou dos 8,4 mil óbitos. Este foi o terceiro maior registro desde o início da pandemia. Mais de 70 mil pacientes já se recuperaram da doença. A Secretaria de Saúde esclareceu que os casos e óbitos registrados no boletim não ocorreram nas últimas 24 horas – essa é a data de registro no sistema.", "img/graficorj", "video/casoscoronavirusrj.mp4", "Rio de Janeiro", "18/06")
exnot3 = Noticia(3, "Pesquisa identifica três linhagens do coronavirus no Amazonas", "O novo coronavírus, sem dúvida surpreendeu o mundo inteiro e por se tratar de algo inédito e sem um conhecimento prévio por parte das entidades de saúde, a cada dia esse vírus vai ganhando novos estudos e algumas informações sobre sua origem vão sendo desvendadas.O Amazonas sofreu e vem sofrendo com a proliferação desse vírus. De acordo com o boletim epidemiológico da Fundação de Vigilância em Saúde, emitido nesta terça-feira (15) aponta que o estado tem 85 mil casos de Covid-19 e que 3.064 pessoas já morreram devido à doença.Uma pesquisa feita pela Fiocruz (Fundação Oswaldo Cruz) em amostras de pacientes infectados nos estados do Amazonas e de Rondônia identificou três linhagens diferentes do novo coronavírus circulam ou circularam na Amazônia desde a chegada do vírus no país.A análise dos genomas indica que a Covid-19 deve ter sido importada de países da Europa, mas de locais diferentes. Com isso, sabe-se que o vírus teve ao menos três entradas diferentes na região. Os estudos agora seguem para saber não só a origem exata, mas a data de chegada à região.Não sabemos ainda se foi direto do Amazonas para Rondônia, ou ao contrário; ou se as linhagens B1 e B1.1 são uma coincidência, diz o pesquisador da Fiocruz Amazônia e coordenador do estudo no Amazonas, Felipe Naveca. A pesquisa no estado conta com a parceria da Fundação de Vigilância em Saúde do Amazonas e o apoio da Fapeam (Fundação de Amparo à Pesquisa do Estado do Amazonas), por meio da Rede Genômica de Vigilância em Saúde.Naveca explica que os vírus B1 e B1.1 têm maior circulação no Reino Unido, Estados Unidos e Austrália. O B.1.1 já é um derivado de B.1. Usamos essa informação para nos ajudar a traçar a rota por onde os vírus passaram, diz. Além deles, em Manaus ainda foi achado o tipo A2, mas que teve uma circulação menor e, ao que tudo indica, não saiu da capital. Esse vírus circulou basicamente em Espanha, Reino Unido e Austrália. Em regra, não se sabe se algum tipo é mais grave que outro. Até agora ninguém conseguiu mostrar uma relação entre linhagem e gravidade, explica.O sequenciamento revelou que dois tipos de vírus diferentes chegaram a cidades pequenas do estado, como Manaquiri (que tem 33 mil habitantes). Todos os tipos tiveram origem na Ásia como ancestral. Na verdade, mesmo sendo uma linhagem europeia, é possível que tenha vindo de outros locais. Nós estamos conduzindo essas análises mais refinadas agora no sentido de inferir a origem mais precisamente, conta.", "img/fiocruzam.png", "video/linhagemcovidam.mp4", "Amazonas", "24/07")
exnot4 = Noticia(4, "Com queda de números em junho, especialistas enxergam padrão de imunidade de rebanho e 'desaceleração' da Covid-19 no AM", "Depois do pico de casos de Covid-19 no Amazonas em maio, há quase cinco semanas o estado apresenta redução progressiva nos números de novos diagnosticados e mortos. Para explicar o cenário no estado, especialistas apontam como uma das explicações a imunidade de rebanho - estratégia que parte do princípio de que, uma vez que grande parte da população já tenha sido infectada, indivíduos ainda vulneráveis têm menor chance de contágio.Com mais de 81 mil casos do novo coronavírus e 2,9 mil mortes, o Amazonas enfrentou seu pico no final de maio, quando registrou mais de 11 mil casos em sete dias. Na última semana epidemiológica (21 a 27 de junho) analisada pela Fundação de Vigilância em Saúde (FVS-AM), 6.120 novos casos foram registrados - uma redução de 11% em relação à semana anterior, mantendo a tendência de queda. Tudo isso aconteceu ao longo de junho, mês de retomada do comércio no estado.Para o infectologista Julio Croda, pesquisador da Fiocruz e ex-diretor do Departamento de Imunização e Doenças Transmissíveis do Ministério da Saúde durante a gestão do ex-ministro Luiz Henrique Mandetta, no paralelo entre a retomada das atividades não essenciais em Manaus com suscetivas quedas de novos casos indica que a população esteja adquirindo a imunidade de rebanho. Ao analisar o cenário atual, ele descarta a chance de outro pico de Covid-19 na capital.", "img/contencaoam.jpg", "video/", "Amazonas", "10/07")

listaNoticias = [exnot1,exnot2,exnot3,exnot4]

exest1 = Estado(1,"Rio de Janeiro", "RJ", 'img/bandrio.png', [exnot1,exnot2])
exest2 = Estado(2,"Amazonas", "AM", 'img/bandamazonas.png', [exnot3,exnot4])
listaEstados = [exest1,exest2]


from app.controller import controllerIndex
from app.controller import controllerEstado
from app.controller import controllerNoticia



